### ISSUE TITLE
Admins are not receiving notifications from video:expired:remove and video:expired:delete

### ISSUE THREAD

**Issue by iriadp** [teltek/PumukitExpiredVideoBundle#44]
There are some notifications for administrators for when a video has expired and it will be deleted.
They are not sent correctly.

Steps:
- Create a new MO with a close expiration date.
- Wait until the expiration day.
- Wait until it is removed.

Expected behaviour:
As admin you should receive an email with information about these videos that will be deleted soon and, after that, another email with information about these videos that have been deleted.
Actual behaviour: 
Both emails are not correctly received.

**Comment by Yurujai** [comment]
Fixed on master. Next release will have this functionality
